### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by kdykeman** [ehowe/vhd-ruby#2]
Can you add something indicating the licensing terms under which this rubygem may be used?

**Comment by AbelHu** [comment]
@ehowe Thanks for your help to merge my change and release vhd-ruby 0.0.4. Now we still need your help to clarify the licensing terms. Expect your response. Thanks.

**Comment by ehowe** [comment]
Sorry @AbelHu, I didn't notice the message from December.  I uploaded a LICENSE file to clarify that.  It's just a 2 clause BSD style license.

**Comment by kdykeman** [comment]
Perfect!  Thanks @ehowe.

**Comment by AbelHu** [comment]
Thanks, @ehowe!
